[project]
name = "NovaOS"
arch = "x86_64"

[toolchain]
cc = "clang"
linker = "ld.lld"

common_cflags = [
    "-ffreestanding",
    "-fno-stack-protector",
    "-fno-builtin",
    "-fno-pic",
    "-fno-pie",
    "-mno-red-zone",
    "-Wall",
    "-Wextra",
    "-Iinclude"
]

# ==========================================
# TARGET 1: UEFI BOOTLOADER
# ==========================================
[targets.boot]
type = "uefi"

dirs = [
    "arch/${arch}/boot"
]

cflags = [
    "--target=${arch}-unknown-windows",
    "-fshort-wchar",
    "-fms-extensions"
]

linker = "lld-link"
ldflags = [
    "-entry:EfiMain",
    "-subsystem:efi_application",
    "-dll"
]

# ==========================================
# TARGET 2: OS KERNEL
# ==========================================
[targets.kernel]
type = "elf"

dirs = [
    "kernel",
]

cflags = [
    "-m64"
]

linker = "ld.lld"
ldflags = [
    "-T", "kernel/linker.ld"
]
