import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

# Root directory of project (NovaOS)
BASE_DIR = Path(__file__).parent.parent.resolve()
CONFIG_PATH = BASE_DIR / "nova_build.toml"
BUILD_DIR = BASE_DIR / "build"
NINJA_FILE = BASE_DIR / "build.ninja"


def load_config():
    if not CONFIG_PATH.exists():
        print(f"Error: Configuration file '{CONFIG_PATH}' not found!")
        sys.exit(1)

    with open(CONFIG_PATH, "rb") as f:
        return tomllib.load(f)


def generate_ninja():
    config = load_config()

    toolchain = config.get("toolchain", {})
    default_cc = toolchain.get("cc", "clang")
    default_linker = toolchain.get("linker", "ld.lld")

    ninja_lines = [
        "# Generated by NovaBuild",
        "ninja_required_version = 1.3\n",
        "# Global rules compilaton and link",
        "rule cc",
        "  command = $cc $cflags -c $in -o $out",
        "  description = CC $in\n",
        "rule link_gnu",
        "  command = $linker $ldflags $in -o $out",
        "  description = LINK $out\n",
        "rule link_msvc",
        "  command = $linker $ldflags $in -out:$out",
        "  description = LINK $out\n",
    ]

    all_outputs = []

    for target_name in ["boot", "kernel"]:
        if target_name not in config:
            continue
        # Find targets
        target_config = config[target_name]
        cc = target_config.get("cc", default_cc)
        cflags = " ".join(target_config.get("cflags", []))
        linker = target_config.get("linker", default_linker)
        ldflags = " ".join(target_config.get("ldflags", []))
        sources = target_config.get("sources", [])

        # Find files
        resolved_sources = []
        for src_str in sources:
            if "*" in src_str or "?" in src_str:
                resolved_sources.extend(sorted(BASE_DIR.glob(src_str)))
            else:
                p = BASE_DIR / src_str
                if p.exists():
                    resolved_sources.append(p)

        resolved_sources = list(dict.fromkeys(resolved_sources))

        # Add object files
        target_obj_dir = Path("build") / "obj" / target_name
        objects = []

        for src in resolved_sources:
            rel_src = src.relative_to(BASE_DIR)
            obj = target_obj_dir / (src.stem + ".o")
            objects.append(str(obj))

            ninja_lines.append(f"build {obj}: cc {rel_src}")
            ninja_lines.append(f"  cc = {cc}")
            ninja_lines.append(f"  cflags = {cflags}")

        # Add executable
        target_type = target_config.get("type", "")
        if target_type == "uefi":
            out_dir = Path("build") / "EFI" / "BOOT"
            out_dir.mkdir(parents=True, exist_ok=True)
            out_bin = out_dir / "BOOTX64.EFI"
        else:
            out_bin = Path("build") / f"{target_name}"
        all_outputs.append(str(out_bin))

        # Add obj info & info linker & info flags
        is_msvc_linker = "lld-link" in linker or "link" in linker.lower()
        rule_name = "link_msvc" if is_msvc_linker else "link_gnu"

        objs_str = " ".join(objects)
        ninja_lines.append(f"build {out_bin}: {rule_name} {objs_str}")
        ninja_lines.append(f"  linker = {linker}")
        ninja_lines.append(f"  ldflags = {ldflags}\n")

    # What default should compiling ninja
    ninja_lines.append(f"default {' '.join(all_outputs)}")

    with open(NINJA_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(ninja_lines) + "\n")

    print(f"Generated {NINJA_FILE.name}")


def generate_compile_commands():
    res = subprocess.run(
        ["ninja", "-t", "compdb", "cc"],
        cwd=BASE_DIR,
        capture_output=True,
        text=True,
    )
    if res.returncode == 0:
        compdb_path = BASE_DIR / "compile_commands.json"
        with open(compdb_path, "w", encoding="utf-8") as f:
            f.write(res.stdout)
        print("Generated compile_commands.json for clangd")


def build():
    generate_ninja()

    print("\nStarting Ninja...")
    res = subprocess.run(["ninja"], cwd=BASE_DIR)

    if res.returncode == 0:
        generate_compile_commands()
        print("\nBuild success!")
    else:
        print("\nBuild failed!")


def clean():
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
        print("Directory 'build' cleaned.")

    if NINJA_FILE.exists():
        NINJA_FILE.unlink()
        print("File 'build.ninja' cleaned.")

    compdb_path = BASE_DIR / "compile_commands.json"
    if compdb_path.exists():
        compdb_path.unlink()
        print("File 'compile_commands.json' cleaned.")


def main():
    print("NovaBuild started")
    if len(sys.argv) > 1 and sys.argv[1] == "clean":
        print("Clean")
        clean()
    else:
        print("Build")
        build()


if __name__ == "__main__":
    main()

